AWSTemplateFormatVersion: 2010-09-09
Parameters:
  RawBucket:
    Description: Name of the Bucket to store the Raw data.
    Default: glue-crawler-datasets
    Type: String
  PublicKeyParameter:
    Type: String
    Description: Public SSH Key for Creating an AWS Glue Development Endpoint.
  OutputBucketParameter:
    Type: String
    Default: glue-crawler-output
    Description: S3 bucket for script output. This is used to grant write permissions
      to the role created by this template.
  OutputPrefixParameter:
    Type: String
    Default: script
    Description: S3 prefix for script output. This is used to grant write permissions
      to the role created by this template.
Resources:
  GlueRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - glue.amazonaws.com
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      - arn:aws:iam::aws:policy/service-role/AWSGlueServiceNotebookRole
      Policies:
      - PolicyName: SourceS3Access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - s3:ListBucket
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:s3:::${RawBucket}
            Condition:
              StringEquals:
                s3:prefix: examples/
          - Action:
            - s3:GetObject
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:s3:::${RawBucket}/examples/*
      - PolicyName: OutputS3Access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - s3:ListBucket
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:s3:::${OutputBucketParameter}
            Condition:
              StringEquals:
                s3:prefix:
                  Fn::Sub: ${OutputPrefixParameter}
          - Action:
            - s3:GetObject
            - s3:DeleteObject
            - s3:PutObject
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:s3:::${OutputBucketParameter}/*
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - Ref: GlueRole
      InstanceProfileName:
        Ref: GlueRole
  PartitionDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId:
        Ref: AWS::AccountId
      DatabaseInput:
        Name: glue-canvas
        Description: Database for Glue Partition blog post example.
  PartitionCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Role:
        Fn::GetAtt:
        - GlueRole
        - Arn
      Description: A Crawler for the Sample GitHub monthly dataset.
      DatabaseName:
        Ref: PartitionDatabase
      Targets:
        S3Targets:
        - Path:
            Ref: RawBucket
  PartitionDevEndpoint:
    Type: AWS::Glue::DevEndpoint
    Properties:
      EndpointName: partition-endpoint
      PublicKey:
        Ref: PublicKeyParameter
      RoleArn:
        Fn::GetAtt:
        - GlueRole
        - Arn
