version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sqs-to-firehose"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-myor7j3zui4c"
s3_prefix = "sqs-to-firehose"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FirehoseDeliveryStreamARN=\"arn:aws:firehose:us-east-2:430229884637:deliverystream/sam-lrs-data-pipeline-DeliveryStream-8M7sKQ88lQhF\" LambdaMonitorTemplateURL=\"\" LambdaMonitorAlarmTopicARN=\"\" LogSubscriptionARN=\"\" LogKMSKeyARN=\"\""
